---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: password-manager-api-hpa
  namespace: password-manager
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: password-manager-api
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 300
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 800
