---
apiVersion: v1
kind: Service
metadata:
  namespace: password-manager
  name: password-manager-svc
spec:
  ports:
  - port: 8080
  selector:
    app: password-manager-api
  type: NodePort                 # NodePort only for minikube, on prod env, ClusterIP + Ingress is better solution
