---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-manager-api
  namespace: password-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: password-manager-api
  template:
    metadata:
      name: password-manager-api-pod
      labels:
        app: password-manager-api
        external-svc: redis-server-password-manager
    spec:
      containers:
        - name: password-manager-api
          image: wojtek9502/password-manager-api
          command: ["/bin/bash" ]
          args: ["-c", "alembic upgrade head && python run_server.py --port 8080"]
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 10
            initialDelaySeconds: 8
          envFrom:
            - configMapRef:
                name: password-manager-api-configmap
          resources:
            requests:
              cpu: '200m'
              memory: '300Mi'
            limits:
              cpu: '500m'
              memory: '1500Mi'